### ISSUE TITLE
fails to build with swagger2-2.16

### ISSUE THREAD

**Issue by juhp** [wereHamster/avers#2]
```
Building library for avers-api-docs-0.0.18.0..
[1 of 1] Compiling Avers.API.Documentation ( src/Avers/API/Documentation.hs, dist/build/Avers/API/Documentation.o )

src/Avers/API/Documentation.hs:55:7: error:
    Ambiguous occurrence ‘fieldLabelModifier’
    It could refer to either ‘Data.Swagger.fieldLabelModifier’,
                             imported from ‘Data.Swagger’ at src/Avers/API/Documentation.hs:22:1-60
                             (and originally defined in ‘Data.Swagger.SchemaOptions’)
                          or ‘Data.Aeson.fieldLabelModifier’,
                             imported from ‘Data.Aeson’ at src/Avers/API/Documentation.hs:23:1-27
                             (and originally defined in ‘aeson-1.2.2.0:Data.Aeson.Types.Internal’)
   |
55 |     { fieldLabelModifier     = dropPrefix p
   |       ^^^^^^^^^^^^^^^^^^

src/Avers/API/Documentation.hs:56:7: error:
    Ambiguous occurrence ‘constructorTagModifier’
    It could refer to either ‘Data.Swagger.constructorTagModifier’,
                             imported from ‘Data.Swagger’ at src/Avers/API/Documentation.hs:22:1-60
                             (and originally defined in ‘Data.Swagger.SchemaOptions’)
                          or ‘Data.Aeson.constructorTagModifier’,
                             imported from ‘Data.Aeson’ at src/Avers/API/Documentation.hs:23:1-27
                             (and originally defined in ‘aeson-1.2.2.0:Data.Aeson.Types.Internal’)
   |
56 |     , constructorTagModifier = map toLower
   |       ^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by juhp** [comment]
See also fpco/stackage#2895
